# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BEM(object):
    def setupUi(self, BEM):
        BEM.setObjectName("BEM")
        BEM.resize(465, 434)
        self.centralwidget = QtWidgets.QWidget(BEM)
        self.centralwidget.setObjectName("centralwidget")
        self.numPanelLabel = QtWidgets.QLabel(self.centralwidget)
        self.numPanelLabel.setGeometry(QtCore.QRect(10, 30, 151, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.numPanelLabel.setFont(font)
        self.numPanelLabel.setScaledContents(True)
        self.numPanelLabel.setWordWrap(True)
        self.numPanelLabel.setObjectName("numPanelLabel")
        self.airfoilLabel = QtWidgets.QLabel(self.centralwidget)
        self.airfoilLabel.setEnabled(True)
        self.airfoilLabel.setGeometry(QtCore.QRect(10, 130, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.airfoilLabel.setFont(font)
        self.airfoilLabel.setMouseTracking(False)
        self.airfoilLabel.setTabletTracking(False)
        self.airfoilLabel.setScaledContents(True)
        self.airfoilLabel.setWordWrap(True)
        self.airfoilLabel.setObjectName("airfoilLabel")
        self.numPanel = QtWidgets.QLineEdit(self.centralwidget)
        self.numPanel.setGeometry(QtCore.QRect(160, 60, 211, 31))
        self.numPanel.setObjectName("numPanel")
        self.airfoilData = QtWidgets.QLineEdit(self.centralwidget)
        self.airfoilData.setGeometry(QtCore.QRect(160, 150, 211, 31))
        self.airfoilData.setObjectName("airfoilData")
        self.PanelOK = QtWidgets.QPushButton(self.centralwidget)
        self.PanelOK.setGeometry(QtCore.QRect(380, 60, 75, 31))
        self.PanelOK.setObjectName("PanelOK")
        self.airfoilOK = QtWidgets.QPushButton(self.centralwidget)
        self.airfoilOK.setGeometry(QtCore.QRect(380, 150, 75, 31))
        self.airfoilOK.setObjectName("airfoilOK")
        self.CLLabel = QtWidgets.QLabel(self.centralwidget)
        self.CLLabel.setGeometry(QtCore.QRect(40, 250, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.CLLabel.setFont(font)
        self.CLLabel.setObjectName("CLLabel")
        self.outCL = QtWidgets.QLineEdit(self.centralwidget)
        self.outCL.setGeometry(QtCore.QRect(160, 260, 211, 31))
        self.outCL.setObjectName("outCL")
        self.downloadCP = QtWidgets.QPushButton(self.centralwidget)
        self.downloadCP.setGeometry(QtCore.QRect(100, 330, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.downloadCP.setFont(font)
        self.downloadCP.setObjectName("downloadCP")
        BEM.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BEM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 21))
        self.menubar.setObjectName("menubar")
        BEM.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BEM)
        self.statusbar.setObjectName("statusbar")
        BEM.setStatusBar(self.statusbar)

        self.retranslateUi(BEM)
        QtCore.QMetaObject.connectSlotsByName(BEM)

    def retranslateUi(self, BEM):
        _translate = QtCore.QCoreApplication.translate
        BEM.setWindowTitle(_translate("BEM", "2DBEM"))
        self.numPanelLabel.setText(_translate("BEM", "Panel 數量"))
        self.airfoilLabel.setText(_translate("BEM", "翼型檔案"))
        self.PanelOK.setText(_translate("BEM", "OK"))
        self.airfoilOK.setText(_translate("BEM", "OK"))
        self.CLLabel.setText(_translate("BEM", "CL : "))
        self.downloadCP.setText(_translate("BEM", "下載-Cp圖"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BEM = QtWidgets.QMainWindow()
    ui = Ui_BEM()
    ui.setupUi(BEM)
    BEM.show()
    sys.exit(app.exec_())
