from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(550, 780)
        
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Message_Box = QtWidgets.QGroupBox(self.centralwidget)
        self.Message_Box.setGeometry(QtCore.QRect(20, 20, 511, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.Message_Box.setFont(font)
        self.Message_Box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Message_Box.setAutoFillBackground(False)
        self.Message_Box.setFlat(False)
        self.Message_Box.setCheckable(False)
        self.Message_Box.setObjectName("Message_Box")
        self.Message_Label = QtWidgets.QLabel(self.Message_Box)
        self.Message_Label.setGeometry(QtCore.QRect(30, 30, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.Message_Label.setFont(font)
        self.Message_Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Message_Label.setObjectName("Message_Label")
        self.Parameters_Box = QtWidgets.QGroupBox(self.centralwidget)
        self.Parameters_Box.setGeometry(QtCore.QRect(20, 100, 511, 211))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.Parameters_Box.setFont(font)
        self.Parameters_Box.setObjectName("Parameters_Box")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Parameters_Box)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 30, 401, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(10, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.StreamVelocity_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StreamVelocity_Label.setFont(font)
        self.StreamVelocity_Label.setObjectName("StreamVelocity_Label")
        self.gridLayout.addWidget(self.StreamVelocity_Label, 1, 0, 1, 1)
        self.Angle_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Angle_Label.setFont(font)
        self.Angle_Label.setObjectName("Angle_Label")
        self.gridLayout.addWidget(self.Angle_Label, 0, 0, 1, 1)
        self.Velocity_Input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Velocity_Input.setObjectName("Velocity_Input")
        self.gridLayout.addWidget(self.Velocity_Input, 1, 1, 1, 1)
        self.Panels_Input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Panels_Input.setObjectName("Panels_Input")
        self.gridLayout.addWidget(self.Panels_Input, 2, 1, 1, 1)
        self.Angle_Input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Angle_Input.setObjectName("Angle_Input")
        self.gridLayout.addWidget(self.Angle_Input, 0, 1, 1, 1)
        self.Panels_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Panels_Label.setFont(font)
        self.Panels_Label.setObjectName("Panels_Label")
        self.gridLayout.addWidget(self.Panels_Label, 2, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 5)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Parameters_Box)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(410, 30, 95, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Angle_Ok = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Angle_Ok.setFont(font)
        self.Angle_Ok.setObjectName("Angle_Ok")
        self.verticalLayout_2.addWidget(self.Angle_Ok)
        self.Velocity_Ok = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Velocity_Ok.setFont(font)
        self.Velocity_Ok.setObjectName("Velocity_Ok")
        self.verticalLayout_2.addWidget(self.Velocity_Ok)
        self.Panels_Ok = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Panels_Ok.setFont(font)
        self.Panels_Ok.setObjectName("Panels_Ok")
        self.verticalLayout_2.addWidget(self.Panels_Ok)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 320, 511, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Load = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.Load.setFont(font)
        self.Load.setObjectName("Load")
        self.horizontalLayout.addWidget(self.Load)
        self.PLOT = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.PLOT.setFont(font)
        self.PLOT.setObjectName("PLOT")
        self.horizontalLayout.addWidget(self.PLOT)
        self.Calculation = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.Calculation.setFont(font)
        self.Calculation.setObjectName("Calculation")
        self.horizontalLayout.addWidget(self.Calculation)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 380, 511, 211))
        self.graphicsView.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 610, 511, 131))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 30, 258, 91))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.CL_Label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.CL_Label.setObjectName("CL_Label")
        self.gridLayout_2.addWidget(self.CL_Label, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(320, 30, 173, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.CP_Contour_Plot = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.CP_Contour_Plot.setObjectName("CP_Contour_Plot")
        self.verticalLayout_3.addWidget(self.CP_Contour_Plot)
        self.Download = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Download.setObjectName("Download")
        self.verticalLayout_3.addWidget(self.Download)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "2DBEM"))
        self.Message_Box.setTitle(_translate("mainWindow", "Message"))
        self.Message_Label.setText(_translate("mainWindow", "NO MESSAGES"))
        self.Parameters_Box.setTitle(_translate("mainWindow", "Parameters"))
        self.StreamVelocity_Label.setText(_translate("mainWindow", "Free Stream Velocity [m/s]"))
        self.Angle_Label.setText(_translate("mainWindow", "Airfoil Angle of Attack [°]"))
        self.Panels_Label.setText(_translate("mainWindow", "Numbers of Panels"))
        self.Angle_Ok.setText(_translate("mainWindow", "OK"))
        self.Velocity_Ok.setText(_translate("mainWindow", "OK"))
        self.Panels_Ok.setText(_translate("mainWindow", "OK"))
        self.Load.setText(_translate("mainWindow", "LOAD"))
        self.PLOT.setText(_translate("mainWindow", "PLOT"))
        self.Calculation.setText(_translate("mainWindow", "Calculation"))
        self.groupBox_3.setTitle(_translate("mainWindow", "Output Data"))
        self.label_6.setText(_translate("mainWindow", "Lift Coefficient (CL)"))
        self.CL_Label.setText(_translate("mainWindow", "None"))
        self.CP_Contour_Plot.setText(_translate("mainWindow", "-CP Contour plot"))
        self.Download.setText(_translate("mainWindow", "Download -CP plot"))
